baseURL = "https://awards.pages.gl.infra.medigy.com/hhs-easy-ehr-issue-reporting-challenge/hhs-easy-ehr-issue-reporting-challenge"
languageCode = "en-us"
title = "Medigy"
theme = ""
[params]
  brand = "Medigy"
  GraphQLUrl = "https://graphql.next.medigy.com/graphql"
  socialshare = "https://awards.pages.gl.infra.medigy.com/hhs-easy-ehr-issue-reporting-challenge/hhs-easy-ehr-issue-reporting-challenge"
  GoogleCaptchaSite = "6LfB7pMUAAAAAGPYb3zz2z-mwZHjfJkumOnmXvNl"
  GTMCode = "GTM-MRP79T4"
  OWLApiUrl = "https://devl.service.ontology.attest.cloud/"
  siteUrl = "https://awards.pages.gl.infra.medigy.com/hhs-easy-ehr-issue-reporting-challenge/hhs-easy-ehr-issue-reporting-challenge"
  elasticSearchUrl = "https://es.medigy.com/"
  issoUrl = "https://isso.medigy.com/"
[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML","Calendar", "JSON"]
  events = ["HTML","Calendar"]
  section = ["HTML","JSON"]
[outputFormats.Calendar]
  protocol = "https://"
[taxonomies]
  tag = "tags"
  topics = "categories"
  languages = "languages"
  feedsource = "feedsource"
  tenantid = "tenantId"
  recognitions = "recognitions"
  geographyCensusDivisions = "geographyCensusDivisions"
  geographyCensusRegions = "geographyCensusRegions"
  geographyStates = "geographyStates"
  geographyZipCodes = "geographyZipCodes"
  hdoTypes = "hdoTypes"
  institutionTypes = "institutionTypes"
[permalinks]
  news = "/news/:year/:month/:day/:slug/"
  events = "/event/:year/:month/:day/:slug/"
  categories = "/topic/:slug/"
  recognitions = "/recognition/award/:slug/"
[sitemap]
  changefreq = "daily"
  priority = 1.0