baseurl = "https://example.com"
title = "Content Generator Unit Test"
author = "Kaushal Modi"
theme = "hugo-bare-min-theme"

enableEmoji = true
enableGitInfo = true

disableFastRender = true        # Hugo 0.30

pygmentsCodeFences = true       # This applies to Chroma too.
pygmentsUseClasses = true       # This applies to Chroma too.

[taxonomies]
  category = "categories"
  tag = "tags"

[Author]
  name = "Kaushal Modi"

[Social]
  github = "kaushalmodi"

[Params]
  description = "Example site for testing generated content."
  intro = ""
  footer = ""
  # Note: It is *mandatory* to set "url" below if you want to set
  # "md_dir" or "org_dir".
  [Params.source]
    url = "https://github.com/kaushalmodi/hugo-bare-min-theme" # Needed if you want to see .GitInfo for a page
    md_dir = "exampleSite/content"                             # Needed if you want to get a link to Markdown source for each page
    # org_dir = "exampleSite/content-org"                        # Needed if you want to get a link to the Org source (e.g. when using ox-hugo!)
